services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.arcanist
      target: dev
      args:
        NEW_MAMBA_USER_ID: "1000"
        NEW_MAMBA_USER_GID: "1000"
    command: bash scripts/arcanist-runtime-start.sh
    init: true
    ports:
      - "8888:8888"
    volumes:
      - .:/home/mambauser/jupyterlab
    working_dir: /home/mambauser/jupyterlab
